#!/usr/bin/env bash
# Tests for session-lane.sh.
#
# lsof, the stack-down tool and pre-commit are stubbed: a stub lsof reports
# listeners only for ports named in a fixture file, a stub stack tool logs its
# arguments, and a stub pre-commit logs its calls and writes the same marked hook
# file into the same shared git common dir the real one writes to. So slot
# picking, release and the commit-gate install are tested without opening a
# socket, starting a service, or running a linter against a real repository.
set -uo pipefail

SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/../scripts" && pwd)"
readonly SCRIPTS
TEST_DIR=$(mktemp -d)
readonly TEST_DIR
trap 'rm -rf "$TEST_DIR"' EXIT

export HARNESS_WORKSPACE="$TEST_DIR/workspace"
export HERDR_PANE_ID="w9:p9"
export LANE_WORKTREE_ROOT="$TEST_DIR/worktrees"
mkdir -p "$HARNESS_WORKSPACE"

PASS=0; FAIL=0
ok()   { printf '  ok   %s\n' "$1"; PASS=$((PASS + 1)); }
bad()  { printf '  FAIL %s\n' "$1"; FAIL=$((FAIL + 1)); }
check(){ if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (want '$3', got '$2')"; fi; }
has()  { case "$2" in *"$3"*) ok "$1" ;; *) bad "$1 (missing '$3')" ;; esac; }
hasnt(){ case "$2" in *"$3"*) bad "$1 (unexpected '$3')" ;; *) ok "$1" ;; esac; }

# ------------------------------------------------------------------ the stubs

STUB="$TEST_DIR/stub"; mkdir -p "$STUB"
: > "$STUB/busy-ports"
cat > "$STUB/lsof" <<'STUBEOF'
#!/usr/bin/env bash
# Emit a pid only for a port listed as busy. Real lsof exits non-zero when
# nothing listens, and the script relies on that.
port=""
for a in "$@"; do case "$a" in -iTCP:*) port="${a#-iTCP:}" ;; esac; done
grep -qx "$port" "$STUB_BUSY" 2>/dev/null && { printf '4242\n'; exit 0; }
exit 1
STUBEOF
chmod +x "$STUB/lsof"
export STUB_BUSY="$STUB/busy-ports"

cat > "$STUB/stack-down" <<'STUBEOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$STUB_CALLS"
exit 0
STUBEOF
chmod +x "$STUB/stack-down"
export STUB_CALLS="$STUB/calls.log"; : > "$STUB_CALLS"
export LANE_STACK_DOWN="$STUB/stack-down"
export PATH="$STUB:$PATH"

# Stands in for pre-commit. It records where it was called from and what it was
# asked to do, then writes a hook into the git COMMON dir, which is where the
# real pre-commit writes it (pre_commit/commands/install_uninstall.py resolves
# the path with get_git_common_dir). Writing to the same shared place is the
# point: the sharing is the behaviour under test.
cat > "$STUB/pre-commit" <<'STUBEOF'
#!/usr/bin/env bash
printf '%s\t%s\n' "$PWD" "$*" >> "$STUB_PC_CALLS"
if [ "${STUB_PC_FAIL:-0}" = 1 ]; then
  printf 'stub: refusing to install\n' >&2
  exit 1
fi
if [ "${1:-}" = install ]; then
  common=$(git rev-parse --path-format=absolute --git-common-dir) || exit 1
  mkdir -p "$common/hooks"
  hook="$common/hooks/pre-commit"
  # The real install's order, and the reason an unguarded second install is
  # dangerous: it decides whether the hook in place is a stranger's, then opens
  # the file for writing, which truncates it before one byte is written.
  if [ -e "$hook" ] && ! grep -q 'File generated by pre-commit' "$hook"; then
    mv "$hook" "$hook.legacy"
  fi
  : > "$hook"
  [ "${STUB_PC_SLOW:-0}" = 1 ] && sleep 0.4
  printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n' >> "$hook"
  chmod +x "$hook"
  printf 'pre-commit installed at %s\n' "$hook"
fi
exit 0
STUBEOF
chmod +x "$STUB/pre-commit"
export STUB_PC_CALLS="$STUB/pre-commit-calls.log"; : > "$STUB_PC_CALLS"
pc_calls() { wc -l < "$STUB_PC_CALLS" | tr -d ' '; }

# A PATH with every stub except pre-commit, for the case where the binary is not
# installed at all. Renaming the stub would be simpler and wrong: on a machine
# that does have pre-commit, it would expose the real binary and run a linter
# against a fixture repository.
NOPC="$TEST_DIR/nopc"; mkdir -p "$NOPC"
for f in "$STUB"/*; do
  case "$(basename "$f")" in pre-commit) continue ;; esac
  [ -x "$f" ] && ln -sf "$f" "$NOPC/$(basename "$f")"
done
readonly NOPC

# ------------------------------------------------------------------- fixtures

REPO="$TEST_DIR/myrepo"
git init -q -b main "$REPO"
git -C "$REPO" config user.email t@t.t
git -C "$REPO" config user.name t
printf 'x\n' > "$REPO/f.txt"
git -C "$REPO" add f.txt
git -C "$REPO" commit -qm init

lane() { "$SCRIPTS/session-lane.sh" "$@"; }

# ------------------------------------------------------------ input validation

printf 'lane name validation\n'
for badname in 'Alpha' '9lane' 'a b' 'a;rm -rf /' '../etc' '--all-x' ''; do
  EXIT=0; OUT=$(lane up "$badname" --repo "$REPO" 2>&1) || EXIT=$?
  if [ "$EXIT" -ne 0 ]; then ok "refused lane name '$badname'"; else bad "accepted lane name '$badname'"; fi
done
EXIT=0; OUT=$(lane up "$(printf 'a%.0s' {1..40})" --repo "$REPO" 2>&1) || EXIT=$?
check "refused a 40-character lane name" "$EXIT" "1"

printf 'repo validation\n'
EXIT=0; OUT=$(lane up alpha 2>&1) || EXIT=$?
check "--repo is required" "$EXIT" "2"
EXIT=0; OUT=$(lane up alpha --repo "$TEST_DIR/nope" 2>&1) || EXIT=$?
check "a missing repo is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up alpha --repo "$TEST_DIR" 2>&1) || EXIT=$?
check "a non-git directory is refused" "$EXIT" "1"
has "the refusal names the reason" "$OUT" "not a git repository"
EXIT=0; OUT=$(lane up alpha --repo "$REPO" --slot 0 2>&1) || EXIT=$?
check "slot 0 is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up alpha --repo "$REPO" --slot 99 2>&1) || EXIT=$?
check "an out-of-range slot is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up alpha --repo "$REPO" --slot 'x;id' 2>&1) || EXIT=$?
check "an injected slot is refused" "$EXIT" "1"

# --------------------------------------------------------------- allocation

printf 'allocation\n'
OUT=$(lane up alpha --repo "$REPO" 2>&1)
has "reports the lane allocated" "$OUT" "lane alpha allocated"
has "assigns the lowest free slot" "$OUT" "slot 1 (ports 3100 8180 8181)"
has "emits the Resources block" "$OUT" "Resources: worktree"
has "emits the child cwd, not the lead cwd" "$OUT" "--cwd $LANE_WORKTREE_ROOT/myrepo/alpha"
has "emits the naming rule" "$OUT" "-- --name alpha"
check "the worktree exists" "$([ -d "$LANE_WORKTREE_ROOT/myrepo/alpha" ] && echo y)" "y"
check "the branch is per lane" \
  "$(git -C "$LANE_WORKTREE_ROOT/myrepo/alpha" rev-parse --abbrev-ref HEAD)" "lane/alpha"
check "the worktree is registered" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c '^worktree|')" "1"
check "the slot is registered" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c '^slot|1|')" "1"

EXIT=0; OUT=$(lane up alpha --repo "$REPO" 2>&1) || EXIT=$?
check "a duplicate lane is refused" "$EXIT" "1"
has "the refusal says how to release it" "$OUT" "session-lane.sh down alpha"

OUT=$(lane up bravo --repo "$REPO" 2>&1)
has "the second lane gets the next slot" "$OUT" "slot 2 (ports 3200 8280 8281)"
EXIT=0; OUT=$(lane up charlie --repo "$REPO" --slot 1 2>&1) || EXIT=$?
check "a slot taken by this session is refused" "$EXIT" "1"

printf 'a busy port is never trampled\n'
printf '3300\n' > "$STUB_BUSY"
OUT=$(lane up charlie --repo "$REPO" 2>&1)
has "a slot with a listener is skipped" "$OUT" "slot 4"
EXIT=0; OUT=$(lane up delta --repo "$REPO" --slot 3 2>&1) || EXIT=$?
check "an explicit busy slot is refused" "$EXIT" "1"
has "the refusal forbids killing the holder" "$OUT" "do not kill the holder"
: > "$STUB_BUSY"

printf 'a lane on a branch that already exists\n'
# The dcl run on 2026-08-31 bypassed session-lane because the work was on an
# existing feature branch and `up` could only cut a new lane/<name>. A road that
# does not reach the destination gets driven around.
git -C "$REPO" branch -q feature/existing
OUT=$(lane up onexisting --repo "$REPO" --branch feature/existing 2>&1)
has "it allocates on the existing branch" "$OUT" "branch feature/existing"
check "the worktree really is on that branch" \
  "$(git -C "$LANE_WORKTREE_ROOT/myrepo/onexisting" rev-parse --abbrev-ref HEAD)" "feature/existing"
EXIT=0; OUT=$(lane up nosuchbranch --repo "$REPO" --branch does/not/exist 2>&1) || EXIT=$?
check "a branch that does not exist is refused" "$EXIT" "1"
has "and it says how to get the default" "$OUT" "drop --branch"

printf 'adopting a worktree that already exists\n'
git -C "$REPO" worktree add -q "$TEST_DIR/preexisting" -b preexisting
OUT=$(lane up adopted --adopt "$TEST_DIR/preexisting" 2>&1)
has "it reports the adoption" "$OUT" "adopted, worktree left unregistered"
has "it still assigns a slot" "$OUT" "slot"
# The safety property: registration is what permits the close to remove a thing.
check "an adopted worktree is NOT registered for removal" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c 'preexisting' || true)" "0"
# Assert the adopted lane's own slot is registered rather than a total count,
# which would depend on whatever earlier cases left allocated.
ADOPTED_SLOT=$(lane list | awk '$1=="adopted"{print $2}')
check "but its slot is registered" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c "^slot|$ADOPTED_SLOT|")" "1"
EXIT=0; OUT=$(lane up twice --adopt "$TEST_DIR/preexisting" 2>&1) || EXIT=$?
check "the same worktree cannot be adopted twice" "$EXIT" "1"
EXIT=0; OUT=$(lane up bad --adopt "$TEST_DIR/notathing" 2>&1) || EXIT=$?
check "a missing path is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up bad --adopt "$TEST_DIR" 2>&1) || EXIT=$?
check "a non-worktree is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up bad --adopt "$TEST_DIR/preexisting" --branch x 2>&1) || EXIT=$?
check "--adopt with --branch is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane up bad --adopt "$TEST_DIR/preexisting" --base main 2>&1) || EXIT=$?
check "--adopt with --base is refused" "$EXIT" "1"

# Releasing an adopted lane must free the slot and still not touch the checkout.
lane down adopted >/dev/null 2>&1
check "releasing an adopted lane leaves the checkout alone" \
  "$([ -d "$TEST_DIR/preexisting" ] && echo yes)" "yes"
lane down onexisting >/dev/null 2>&1

printf 'list\n'
OUT=$(lane list 2>&1)
has "list shows a lane" "$OUT" "alpha"
has "list shows its ports" "$OUT" "3100 8180 8181"

# ------------------------------------------------------------------ release

printf 'release\n'
: > "$STUB_CALLS"
OUT=$(lane down alpha 2>&1)
has "the stack tool was asked to stop the slot" "$(cat "$STUB_CALLS")" "down --slot 1"
has "reports the slot released" "$OUT" "released slot 1"
check "the slot registration is dropped" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c '^slot|1|' || true)" "0"
check "the lane row is gone" "$(lane list | grep -c 'alpha' || true)" "0"

# The safety property this script is built around.
check "the worktree still exists after release" \
  "$([ -d "$LANE_WORKTREE_ROOT/myrepo/alpha" ] && echo y)" "y"
check "the worktree registration is untouched" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c "worktrees/myrepo/alpha")" "1"
has "release defers the worktree to the cleanup script" "$OUT" "session-cleanup.sh"
hasnt "release never issues a tab close" "$OUT" "herdr tab close"

printf 'release warns when the ports are still held\n'
printf '3200\n' > "$STUB_BUSY"
OUT=$(lane down bravo 2>&1)
has "a still-listening port is reported" "$OUT" "still has listeners"
: > "$STUB_BUSY"

EXIT=0; OUT=$(lane down nosuch 2>&1) || EXIT=$?
check "an unknown lane is refused" "$EXIT" "1"
EXIT=0; OUT=$(lane down 'a;id' 2>&1) || EXIT=$?
check "an injected lane name is refused on release" "$EXIT" "1"

printf 'the kill switch releases every lane\n'
: > "$STUB_CALLS"
OUT=$(lane down --all 2>&1)
has "it names the remaining lane" "$OUT" "lane charlie"
has "it points at the cleanup script for panes" "$OUT" "session-cleanup.sh --apply"
check "no lanes remain" "$(lane list)" "no lanes allocated"
OUT=$(lane down --all 2>&1)
check "a second run is safe" "$OUT" "no lanes allocated"

# ------------------------------------------- identity survives the lead (P0)
#
# The audit on 2026-08-30 found the emergency stop silently did nothing from any
# shell but the lead's own pane, because the registry was keyed to HERDR_PANE_ID.
# It reported success while the ports stayed held. These are the tests that were
# missing, written so that regression cannot come back unnoticed.

printf 'the registry outlives the pane that wrote it\n'
: > "$STUB_BUSY"
HERDR_PANE_ID="wA:p1" lane up echo1 --repo "$REPO" >/dev/null 2>&1
HERDR_PANE_ID="wA:p1" lane up echo2 --repo "$REPO" >/dev/null 2>&1

OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" list 2>&1)
has "another shell sees the lanes" "$OUT" "echo1"
has "another shell sees the owner" "$OUT" "wAp1"

OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" list --mine 2>&1)
hasnt "--mine hides another pane's lanes" "$OUT" "echo1"

# Ownership is respected by the polite path...
OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" down --mine 2>&1)
check "--mine releases nothing that belongs to another pane" \
  "$(HERDR_PANE_ID="wA:p1" "$SCRIPTS/session-lane.sh" list | grep -c 'echo1')" "1"

# ...and deliberately ignored by the emergency stop, which is the whole point.
OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" down --all 2>&1)
has "the stop says it ignores ownership" "$OUT" "whoever created it"
has "the stop names the dead pane's lane" "$OUT" "echo1"
check "the stop actually emptied the registry" \
  "$(HERDR_PANE_ID="wA:p1" "$SCRIPTS/session-lane.sh" list)" "no lanes allocated"

printf 'a slot held by another pane is not handed out twice\n'
HERDR_PANE_ID="wA:p1" lane up solo --repo "$REPO" >/dev/null 2>&1
EXIT=0; OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" up clash --repo "$REPO" --slot 1 2>&1) || EXIT=$?
check "another pane cannot take a slot already allocated" "$EXIT" "1"
OUT=$(HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" up next --repo "$REPO" 2>&1)
has "it is handed the next free slot instead" "$OUT" "slot 2"
HERDR_PANE_ID="wB:p9" "$SCRIPTS/session-lane.sh" down --all >/dev/null 2>&1

printf 'the stop clears the owning pane artifact row, not the caller one\n'
# Found by the game day: `down --all` from another shell released the slot but
# left its artifact registration behind, because session-artifact.sh keys its
# file to the calling pane. The same class as the P0, in a different file.
: > "$STUB_BUSY"
HERDR_PANE_ID="wC:p1" lane up owned1 --repo "$REPO" >/dev/null 2>&1
check "the owner registered a slot" \
  "$(HERDR_PANE_ID="wC:p1" "$SCRIPTS/session-artifact.sh" list | grep -c '^slot|')" "1"
HERDR_PANE_ID="wD:p2" "$SCRIPTS/session-lane.sh" down --all >/dev/null 2>&1
check "a stop from another shell clears the owning pane slot row" \
  "$(HERDR_PANE_ID="wC:p1" "$SCRIPTS/session-artifact.sh" list | grep -c '^slot|' || true)" "0"
check "and leaves no row in the caller own file" \
  "$(HERDR_PANE_ID="wD:p2" "$SCRIPTS/session-artifact.sh" list | grep -c '^slot|' || true)" "0"

printf 'the registry lives at a well-known path\n'
check "one shared registry, not one per pane" \
  "$(find "$HARNESS_WORKSPACE" -name 'lanes' -type f | wc -l | tr -d ' ')" "1"
check "no pane-keyed lane file exists" \
  "$(find "$HARNESS_WORKSPACE" -name '*.lanes' | wc -l | tr -d ' ')" "0"

# ---------------------------------------------------------- the commit gate
#
# A repository that ships a .pre-commit-config.yaml expects a human to
# run `pre-commit install`. A worktree this script cuts never had that run, so
# the lane commits through a gate that is not there. These cover the install, and
# above all the cases where it must NOT write: the hooks directory is shared with
# the parent checkout and every sibling lane of the same repository.

printf 'the commit gate\n'

new_repo() {
  local r="$1"
  git init -q -b main "$r"
  git -C "$r" config user.email t@t.t
  git -C "$r" config user.name t
  printf 'x\n' > "$r/f.txt"
  git -C "$r" add f.txt
  git -C "$r" commit -qm init
}

HOOKREPO="$TEST_DIR/hookrepo"
new_repo "$HOOKREPO"
printf 'repos: []\n' > "$HOOKREPO/.pre-commit-config.yaml"
git -C "$HOOKREPO" add .pre-commit-config.yaml
git -C "$HOOKREPO" commit -qm hooks
HOOKDIR="$HOOKREPO/.git/hooks"

# The ports column is three space-separated numbers, so count from the end: the
# worktree path is the last column and the hook status is the one before it.
hook_status() { lane list | awk -v l="$1" '$1 == l { print $(NF - 1) }'; }

printf 'a repo with no config\n'
: > "$STUB_PC_CALLS"
OUT=$(lane up nocfg --repo "$REPO" 2>&1)
has "it reports no hooks to install" "$OUT" "Commit hooks (pre-commit): none"
check "list records it as none" "$(hook_status nocfg)" "none"
check "pre-commit was never called" "$(pc_calls)" "0"
lane down nocfg >/dev/null 2>&1

printf 'the skip override\n'
: > "$STUB_PC_CALLS"
OUT=$(LANE_SKIP_PRECOMMIT=1 lane up skipme --repo "$HOOKREPO" 2>&1)
has "it reports the skip" "$OUT" "Commit hooks (pre-commit): skipped"
check "list records it as skipped" "$(hook_status skipme)" "skipped"
check "the override calls nothing" "$(pc_calls)" "0"
check "and writes no hook" "$([ -e "$HOOKDIR/pre-commit" ] && echo y || echo n)" "n"
lane down skipme >/dev/null 2>&1

printf 'pre-commit is not installed at all\n'
: > "$STUB_PC_CALLS"
EXIT=0
OUT=$(PATH="$NOPC:/usr/bin:/bin" "$SCRIPTS/session-lane.sh" up nopc --repo "$HOOKREPO" 2>&1) || EXIT=$?
check "a missing binary never fails the lane" "$EXIT" "0"
has "it warns that the gate is not there" "$OUT" "pre-commit is not on PATH"
has "and reports the status" "$OUT" "Commit hooks (pre-commit): absent"
check "list records it as absent" "$(hook_status nopc)" "absent"
check "the lane is really allocated" "$([ -d "$LANE_WORKTREE_ROOT/hookrepo/nopc" ] && echo y)" "y"
lane down nopc >/dev/null 2>&1

printf 'the install itself fails\n'
: > "$STUB_PC_CALLS"
EXIT=0; OUT=$(STUB_PC_FAIL=1 lane up pcfail --repo "$HOOKREPO" 2>&1) || EXIT=$?
check "a failed install never fails the lane" "$EXIT" "0"
has "it warns and says the lane still starts" "$OUT" "the lane still starts"
check "list records it as failed" "$(hook_status pcfail)" "failed"
check "it did try once" "$(pc_calls)" "1"
lane down pcfail >/dev/null 2>&1

printf 'a hook the user wrote by hand is never displaced\n'
# The crux. .git/hooks is the git COMMON dir, shared with the parent checkout and
# every sibling lane, and pre-commit MOVES a hook it did not generate to
# <hook>.legacy. A lane must not quietly retire a hook Ali wrote, in a repo he is
# not even working in.
: > "$STUB_PC_CALLS"
printf '#!/bin/sh\necho mine\n' > "$HOOKDIR/pre-commit"
chmod +x "$HOOKDIR/pre-commit"
OUT=$(lane up foreignhook --repo "$HOOKREPO" 2>&1)
has "it names the hook it refused to touch" "$OUT" "was not generated by pre-commit"
has "and reports the status" "$OUT" "Commit hooks (pre-commit): foreign"
check "list records it as foreign" "$(hook_status foreignhook)" "foreign"
check "the install was never attempted" "$(pc_calls)" "0"
check "the hand-written hook is untouched" "$(cat "$HOOKDIR/pre-commit")" "$(printf '#!/bin/sh\necho mine')"
check "and nothing was moved aside" "$([ -e "$HOOKDIR/pre-commit.legacy" ] && echo y || echo n)" "n"
lane down foreignhook >/dev/null 2>&1
rm -f "$HOOKDIR/pre-commit"

printf 'the install runs when the way is clear\n'
: > "$STUB_PC_CALLS"
OUT=$(lane up gated --repo "$HOOKREPO" 2>&1)
has "it reports the install" "$OUT" "Commit hooks (pre-commit): installed"
check "list records it as installed" "$(hook_status gated)" "installed"
check "pre-commit was called once" "$(pc_calls)" "1"
has "it was called from the lane worktree, not the lead cwd" \
  "$(cat "$STUB_PC_CALLS")" "hookrepo/gated"
has "and asked to install" "$(cat "$STUB_PC_CALLS")" "install"
check "the hook really exists now" "$([ -x "$HOOKDIR/pre-commit" ] && echo y)" "y"

printf 'the hooks directory is shared, and that is why the guard exists\n'
WTHOOKS=$(git -C "$LANE_WORKTREE_ROOT/hookrepo/gated" rev-parse --path-format=absolute --git-path hooks)
check "a lane hook path resolves into the parent repo common dir" \
  "$WTHOOKS" "$(cd "$HOOKDIR" && pwd -P)"
check "so the parent checkout is gated too" "$([ -x "$HOOKDIR/pre-commit" ] && echo y)" "y"

printf 'a second lane on the same repo writes nothing\n'
: > "$STUB_PC_CALLS"
OUT=$(lane up gated2 --repo "$HOOKREPO" 2>&1)
has "it reports the hooks already present" "$OUT" "Commit hooks (pre-commit): present"
check "list records it as present" "$(hook_status gated2)" "present"
check "and it did not run the install again" "$(pc_calls)" "0"
lane down gated2 >/dev/null 2>&1
lane down gated >/dev/null 2>&1

printf 'the install lock is released\n'
check "no lock is left behind in the common dir" \
  "$([ -e "$HOOKREPO/.git/.session-lane-hooks.lock" ] && echo y || echo n)" "n"

printf 'the hook types come from the config\n'
# A config that asks for pre-push as well must widen the guard, or a hand-written
# pre-push hook would be moved aside by an install this script called.
TYPEREPO="$TEST_DIR/typerepo"
new_repo "$TYPEREPO"
{ printf 'default_install_hook_types: [pre-commit, pre-push]\n'; printf 'repos: []\n'; } \
  > "$TYPEREPO/.pre-commit-config.yaml"
git -C "$TYPEREPO" add .pre-commit-config.yaml
git -C "$TYPEREPO" commit -qm hooks
printf '#!/bin/sh\necho mine\n' > "$TYPEREPO/.git/hooks/pre-push"
chmod +x "$TYPEREPO/.git/hooks/pre-push"
: > "$STUB_PC_CALLS"
OUT=$(lane up typed --repo "$TYPEREPO" 2>&1)
has "a hand-written hook of a configured type stops the install" "$OUT" "foreign"
check "and that hook is untouched" "$(cat "$TYPEREPO/.git/hooks/pre-push")" \
  "$(printf '#!/bin/sh\necho mine')"
check "nothing was called" "$(pc_calls)" "0"
lane down typed >/dev/null 2>&1

printf 'adopting a worktree installs the gate too\n'
# An adopted checkout commits through the same hooks and has the same hole. The
# rule that keeps --adopt from registering the worktree is about REMOVAL, which
# destroys work; an install is additive, guarded and idempotent.
ADOPTREPO="$TEST_DIR/adoptrepo"
new_repo "$ADOPTREPO"
printf 'repos: []\n' > "$ADOPTREPO/.pre-commit-config.yaml"
git -C "$ADOPTREPO" add .pre-commit-config.yaml
git -C "$ADOPTREPO" commit -qm hooks
git -C "$ADOPTREPO" worktree add -q "$TEST_DIR/adoptwt" -b adoptwt
: > "$STUB_PC_CALLS"
OUT=$(lane up adopthooks --adopt "$TEST_DIR/adoptwt" 2>&1)
has "the adopted lane installs the gate" "$OUT" "Commit hooks (pre-commit): installed"
check "list records it as installed" "$(hook_status adopthooks)" "installed"
check "the hook landed in the adopted repo common dir" \
  "$([ -x "$ADOPTREPO/.git/hooks/pre-commit" ] && echo y)" "y"
check "the adopted checkout is still not registered for removal" \
  "$("$SCRIPTS/session-artifact.sh" list | grep -c 'adoptwt' || true)" "0"
lane down adopthooks >/dev/null 2>&1

printf 'two lanes on one repo cannot corrupt the shared hooks\n'
# The other half of the shared-directory problem. pre-commit truncates the hook
# file before it writes it, so an unguarded second install can read the first one
# half written, judge it a stranger's hook and move the wreckage over the .legacy
# backup. Run two lanes at once against a deliberately slow install and assert
# that exactly one of them wrote, and that what landed is a whole hook.
RACEREPO="$TEST_DIR/racerepo"
new_repo "$RACEREPO"
printf 'repos: []\n' > "$RACEREPO/.pre-commit-config.yaml"
git -C "$RACEREPO" add .pre-commit-config.yaml
git -C "$RACEREPO" commit -qm hooks
: > "$STUB_PC_CALLS"
STUB_PC_SLOW=1 lane up racea --repo "$RACEREPO" --slot 7 >"$TEST_DIR/racea.out" 2>&1 &
RACE_A=$!
STUB_PC_SLOW=1 lane up raceb --repo "$RACEREPO" --slot 8 >"$TEST_DIR/raceb.out" 2>&1 &
RACE_B=$!
EXIT=0; wait "$RACE_A" || EXIT=$?
check "the first lane survived the race" "$EXIT" "0"
EXIT=0; wait "$RACE_B" || EXIT=$?
check "the second lane survived the race" "$EXIT" "0"
check "only one of the two ran the install" "$(pc_calls)" "1"
check "the hook that landed is whole" \
  "$(grep -c 'File generated by pre-commit' "$RACEREPO/.git/hooks/pre-commit")" "1"
check "no backup was clobbered into existence" \
  "$([ -e "$RACEREPO/.git/hooks/pre-commit.legacy" ] && echo y || echo n)" "n"
RACE_OUT=$(cat "$TEST_DIR/racea.out" "$TEST_DIR/raceb.out")
has "one lane installed" "$RACE_OUT" "Commit hooks (pre-commit): installed"
has "and the other found them present" "$RACE_OUT" "Commit hooks (pre-commit): present"
check "the lock is released afterwards" \
  "$([ -e "$RACEREPO/.git/.session-lane-hooks.lock" ] && echo y || echo n)" "n"
lane down racea >/dev/null 2>&1
lane down raceb >/dev/null 2>&1

printf 'the porcelain contract is unchanged\n'
# session-batch.sh reads porcelain rows with `read -r lane slot path _ created`,
# where the last variable absorbs anything extra, so a sixth field would land
# inside the timestamp and cost every new lane its spawn grace period.
lane up shape --repo "$HOOKREPO" >/dev/null 2>&1
ROW=$(lane list --porcelain | grep '^shape|')
check "porcelain still carries exactly five fields" "$(printf '%s' "$ROW" | awk -F'|' '{print NF}')" "5"
hasnt "and the hook status is not one of them" "$ROW" "present"
check "the table does carry it" "$(hook_status shape)" "present"
lane down shape >/dev/null 2>&1

lane down --all >/dev/null 2>&1

# ------------------------------------------------------------ source quality

printf 'source quality\n'
SRC=$(cat "$SCRIPTS/session-lane.sh")
has "strict mode" "$SRC" "set -euo pipefail"
has "readonly constants" "$SRC" "readonly MIN_SLOT"
has "a cleanup trap for the temp file" "$SRC" "trap 'rm -f \"\$tmp\"' EXIT"
has "errors go to stderr through die" "$SRC" "die "
hasnt "it never removes a worktree" "$SRC" "worktree remove"
hasnt "it never closes a pane" "$SRC" "pane close <pane-id>\""
hasnt "the registry is not keyed to a pane" "$SRC" '%s.lanes'
has "the registry is locked for rewrites" "$SRC" "with_lock _drop_lane_row"
has "the skip override is documented in the header" "$SRC" "LANE_SKIP_PRECOMMIT=1 to skip"
has "the shared hooks directory is explained" "$SRC" "Git hooks are NOT per worktree"
has "the hook install takes a lock" "$SRC" 'if ! _acquire_lock "$lock"; then'
has "the hook install cannot fail the lane" "$SRC" 'hooks=$(install_commit_hooks "$path") || hooks=unknown'
hasnt "it never forces an install over a hook it did not write" "$SRC" "pre-commit install -f"

printf '\n%d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
